--- #YAML:1.0
name:               Net-DHCP
version:            0.68
abstract:           Object methods to create a DHCP packet.
author:
    - Dean Hamstead <djzort@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Spec:  0
    Test::More:  0
    Test::Warn:  0
requires:
    Carp:          0
    Exporter:      0
    List::Util:    0
    Scalar::Util:  0
    Socket:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
